<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>All Kotak Drop Down</name>
   <tag></tag>
   <elementGuidId>98ddb322-6eee-4b42-9a9a-fa42ed693b22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-levelAdd-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-levelAdd-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>65500504-72b0-4041-a2b7-222178c9baa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>e7bd89b1-f11c-454b-8cc5-53e1a3ef30d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tree</value>
      <webElementGuid>a844fa3e-fde1-4adf-bce6-9d6b4dde3399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-levelAdd-results</value>
      <webElementGuid>e764351f-fbbb-4d74-9f71-286fb8fea8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9045f710-03d0-400e-be1f-5f9db0382c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>519b5f80-366d-4f45-92df-2b59ed759089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4</value>
      <webElementGuid>defec350-bc09-475c-b3d1-ceca778e2081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-levelAdd-results&quot;)</value>
      <webElementGuid>eda73fbf-b8f9-4b3f-a5bb-13c2fe2bee01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-levelAdd-results']</value>
      <webElementGuid>21bedaab-eeaa-4a8c-badb-d4209bbc339b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/span/span/span[2]/ul</value>
      <webElementGuid>5376038a-d071-4ee2-9f79-7961cdbcf6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>8d33b3a5-f07b-47f8-9a71-222ecc529e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-levelAdd-results' and (text() = 'ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4' or . = 'ISOLevel 1Level 1Level 2Level 2Materi 1Materi 2Materi 3Materi 4')]</value>
      <webElementGuid>397ac2b8-c5f9-4dd8-80c2-ca49a94eba9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
