<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_correctAnswer</name>
   <tag></tag>
   <elementGuidId>1f41dd76-b600-4288-b746-cc9d303c5fdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='correctAnswerAddA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#correctAnswerAddA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26cd5b8c-c7cd-4f6a-891f-d6d892f6e4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>df548268-fd51-4c54-a017-9f7dfd1f0e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>correctAnswer</value>
      <webElementGuid>f04b1b0e-3b6f-40e9-804f-c6493046e185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>correctAnswerAddA</value>
      <webElementGuid>2d6d103d-067c-43ea-9ec6-3c8c2e27bcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1eb5dbb9-46b4-48fa-a4b2-8dba7fc6fa27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;correctAnswerAddA&quot;)</value>
      <webElementGuid>0129e020-2007-4688-bcad-056bbc985623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='correctAnswerAddA']</value>
      <webElementGuid>a204efed-a755-4331-a8bd-1ae97c94b387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAdd']/div[2]/div[5]/div/label/input</value>
      <webElementGuid>249cdb32-b8a4-4f2b-bcbb-a7709180ef4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/input</value>
      <webElementGuid>0e09ef9c-2436-44c5-9652-e460ce0425a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'correctAnswer' and @id = 'correctAnswerAddA']</value>
      <webElementGuid>cc171ed0-8241-42db-8197-17101a90ae78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
